### ISSUE TITLE
Custom entities card

### ISSUE THREAD

**Issue by iantrich** [ciotlosm/custom-lovelace#104]
Create a new custom entities card allowing to control entity attributes for lights (brightness or color) and fans (speed)

Some potential inspiration: https://community.home-assistant.io/t/custom-ui-with-buttons-fan-control/13808/6

Demo Fan/Lights/Switch available: https://www.home-assistant.io/components/demo/

**Comment by iantrich** [comment]
Having learned about how versatile the picture element card can be, I'm not sure if this would be a good use case to work on.

**Comment by ciotlosm** [comment]
Maybe entities card with the new custom rows could be explored as well.
