### ISSUE TITLE
update to 3.0 requires a code to alarm/de-arm

### ISSUE THREAD

**Issue by grantclem** [ciotlosm/custom-lovelace#117]
Currently have and Arlo base station (hub for security cameras) and it appears that the arm/disarm function will only work if you enter some code (any keystroke)... event tho one it is not required/used at the moment. I have set the "hide_keypad: true" and it still requires something and provides the field to do so. It can be a single entry and can be run from the services section.

**Comment by ciotlosm** [comment]
This is a bug and will get corrected in 0.3.1

**Comment by ciotlosm** [comment]
Fixed in 0.3.1
