### ISSUE TITLE
Issue with iOS-Clients

### ISSUE THREAD

**Issue by gcosta74** [ciotlosm/custom-lovelace#125]
With iOS-Devices the customer cards do not work.

iOS still uses Javascript version ES5 and it may be the reason for the error.

Here ist the error of the log-entry
`2018-07-24 23:05:53 ERROR (MainThread) [frontend.js.es5.201807200] https://home.domain.com/local/custom-lovelace/vertical-stack-in-card/vertical-stack-in-card.js:2:14 TypeError: Cannot call a class constructor without |new|
2018-07-24 23:05:54 ERROR (MainThread) [frontend.js.es5.201807200] https://home.domain.com/frontend_es5/9867e07e29bf80655547.chunk.js:2:24111 TypeError: undefined is not an object (evaluating 't._leaflet_pos')
`

**Comment by ciotlosm** [comment]
Known issue, I won't support es5 in my custom cards. Adding es5 support will require external libraries that I don't want to include. 

I am using ES6 (latest) of my IOS (version 11.4) and it's working fine.

Majority of custom cards will probably have a limited lifetime as good functionality will make it to core (where libraries are available and es5 is supported).

**Comment by ciotlosm** [comment]
@gcosta74 I have it set the same under my frontend: section and for me it works without problems. If you just added that you must force a few refreshes to clear cache of the ec5 JS.
