### ISSUE TITLE
Animated weather card

### ISSUE THREAD

**Issue by ciotlosm** [ciotlosm/custom-lovelace#131]
~~https://codepen.io/ste-vg/pen/Gqakbo~~

Better version: https://codepen.io/GooeyIdeas/pen/NRvoQv

**Comment by philhawthorne** [comment]
hey @ciotlosm 

Added the animated weather card, using dark sky instead of yweather (not sure if that's an issue?). Getting the following error

```
cardConfig is not defined
```

Looking at the source code for that card type, I can see the JS variable being referenced, but not set. Unless it is set from a parent?

**Comment by ciotlosm** [comment]
hey @philhawthorne , the card is still in the works. As I mentioned on the show, this is currently being worked on. 

It will probably be ready for use around next week as it needs a build system with the different libraries it needs.

**Comment by philhawthorne** [comment]
Ahhhh right! Clearly I got too excited and want to use it straight away :)

**Comment by VirtualL** [comment]
Wow Looking awesome! 
Waiting for any news :)

**Comment by gohassgo** [comment]
Yeah, this looks awesome. Can't wait!

**Comment by ciotlosm** [comment]
This is going slower than expected because in order to make this work I'd either need a build system or external libraries. I want to keep custom cards limited to 1 file if possible, so already evaluated StencilJS. One solution is to go with webpack but I want to retain the ability for people to read the source as it helps with contributions and debugging. 

I hope I get something working at start of September with an approach that is usable and easy to install for users.

**Comment by ezbe** [comment]
so now we can use it or it still in demo?

**Comment by ciotlosm** [comment]
@ezbe Unfortunately not. Work stagnated and probably will still go slow for a while until I sort my time schedule better.

**Comment by iantrich** [comment]
I believe this fills the need: https://github.com/bramkragten/custom-ui/tree/master/weather-card
