### ISSUE TITLE
Gauge as bar

### ISSUE THREAD

**Issue by DanielXYZ2000** [ciotlosm/custom-lovelace#135]
Is it possible to configure the gauge as a horizontal or vertical bar?

**Comment by ludeeus** [comment]
@DanielXYZ2000 have you considered this card ?
<https://github.com/ciotlosm/custom-lovelace/tree/master/bignumber-card>

**Comment by ciotlosm** [comment]
@DanielXYZ2000 going to close this as it's pretty much what bignumber is for
