### ISSUE TITLE
Thermostat-card - Temperature not centerd in Firefox

### ISSUE THREAD

**Issue by hwikene** [ciotlosm/custom-lovelace#149]
Hi! When testing the thermostar-card on Firefox the temperature is not centerd. i have set `dom.webcomponents.shadowdom.enabled` and `dom.webcomponents.customelements.enabled` to "true". 
When i open it in Chrome. everything works great. 

![bilde](https://user-images.githubusercontent.com/17985923/43544448-31501eb2-95d3-11e8-9113-c20612cf97d8.png)

**Comment by ciotlosm** [comment]
Fixed in 0.0.2
