### ISSUE TITLE
Request: homekit-card

### ISSUE THREAD

**Issue by millercentral** [ciotlosm/custom-lovelace#150]
I love the work you are doing on custom lovelace elements. I thought I would throw in a request for another custom card type: would it be possible to emulate the square button types that the iOS HomeKit UI uses:

[example](https://cdn-images-1.medium.com/max/700/1*Z4QanTlsWCwpKf-REcQ-Pw.png)

Basically it is an element that has a small icon (materialdesignicons would be ideal), location, entity name, and status text. "On (or no state) represented with white background, "off" with a dimmed background and grey font color. 

While I'm not a huge fan of HomeKits automations, I find these kinds of buttons useful on a mobile interface for controlling various items. It would be very cool to see something similar for lovelace.

Thanks for considering!

**Comment by ciotlosm** [comment]
@millercentral a square button is more like a custom element. That is not hard. 

However the pain comes in how to structure multiple of those. At the moment there are a few possibilities:

- use such a custom element on top of picture-elements
- use such custom elements in a custom card with a fluid distribution like glance card
- use such custom elements in a fixed grid (either horizontal + vertical stacks in a panel or a custom grid card) 

There is also https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173/833 to consider that can achieve a similar look.

**Comment by millercentral** [comment]
I think the ideal would be the custom element type in a fluid distribution card, that way it would be easy to flow a bunch of elements from a room in to a single card.

Thanks for the link to the tileboard project, that is interesting as well.

**Comment by ciotlosm** [comment]
I will close this as most custom cards are now moved to https://github.com/custom-cards
