### ISSUE TITLE
Thermostat - Colored only when State On (cool/heat/etc) and Fan On

### ISSUE THREAD

**Issue by kylerw** [ciotlosm/custom-lovelace#154]
To work more closely to how the Nest app functions, the color of the dial should only be blue/orange when set to cool/heat/etc AND the fan is running.

**Comment by jjlawren** [comment]
Agree with color coding, but also remember that not all heating systems utilize fan control.

**Comment by ciotlosm** [comment]
This probably can be done via custom card setting. Probably this will be done after I implement the panel for controlling fan/ operation_mode & stuff.

**Comment by mcinnes01** [comment]
Just wondered if there is any update for this? For central heating, the dial is only orange when the target temperature is above the actual temperature. Will this be catered for? I guess using heat or cool can give you enough information about way the target temperature is going and whether to render blue or orange?

**Comment by ciotlosm** [comment]
@mcinnes01 orange or blue are used when the device is in operation. It's a state of the device. I would avoid calculating this on the UI, as you could have devices (like A/C) that have cycles as well so a device might not be actually on. 

The backend component should in all cases report the state of the device. You have a map that allows you to use any attribute in which the backend reports this state with any custom values. 

Can you post your `dev-info` to see how your current setup is? It might be that you already have support for what you need and it's just a matter of a correct mapping in config.

**Comment by mcinnes01** [comment]
@ciotlosm  this is an example of my nest device:

current_temperature: 17.5 
min_temp: 9 
max_temp: 32 
temperature: 19.5 
operation_mode: heat 
operation_list: off,heat,eco 
away_mode: off 
friendly_name: Upstairs 
supported_features: 1153

As you can see when the mode is set to heat and the temperature is higher than the current_temperature it should be orange, when the temperature is equal or less than the current_temperature it should be black. Not sure what should be done when in eco mode, but off should remain black regardless.

This is my config:

      - type: custom:thermostat-card
        title: Bedroom
        entity: climate.upstairs

**Comment by ciotlosm** [comment]
@mcinnes01 can you also post the 'state' besides the attributes for your thermostat in different working conditions?
