### ISSUE TITLE
Scales off across climate entities

### ISSUE THREAD

**Issue by kylerw** [ciotlosm/custom-lovelace#164]
The set point is the same but the scale on the image is different:

![image](https://user-images.githubusercontent.com/370860/43982196-2068c8e8-9cb2-11e8-9dc5-512e6588037e.png)

70 should be at the same location for each entity

**Comment by ciotlosm** [comment]
@kylerw it really depends on what your climate component reports as min/max. Probably can be added a config option to override that but at the moment it's using what the backend component is reporting. 

You can use dev tools to check what min_temp/max_temp is currently reported on each of your thermostats.

**Comment by ciotlosm** [comment]
@kylerw can you let me know if min/max is identical between thermostats? You can check this in dev-info panel.

**Comment by kylerw** [comment]
Hallway: 50/90
Theo's Room: 64/86
Bonus Bedroom: 64/86

**Comment by kylerw** [comment]
Is that done in the climate entity setup?

**Comment by ciotlosm** [comment]
Yes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ciotlosm** [comment]
I will close this as it's not related to the card. Please reopen if you find it's still a problem after you set min/max in the backend climate entity setup.
