### ISSUE TITLE
[Feature Request] Gauge Card: Need Auto-Resizing

### ISSUE THREAD

**Issue by MwC-Trexx** [ciotlosm/custom-lovelace#169]
It would nice if the gauge card auto-resized when using in Horizontal Stack with >2 gauges.

**Comment by ciotlosm** [comment]
@MwC-Trexx I know, but the at moment you can use the 'scale' option as that works fine. You just need to get the right scale depending on how many you get in the horizontal stack. 

I don't think I'll add this auto scale feature on the current version, maybe if I make an SVG version of it.
