### ISSUE TITLE
[Feature Request] Thermostat-card - Support reading current temperature from different entity

### ISSUE THREAD

**Issue by realroywalker** [ciotlosm/custom-lovelace#177]
It would be great if the thermostat card could support displaying the current temperature from a different entity to the setpoint device.

An optional entity 'temperature_entity' (or something similar) that could be filled in with a temperature sensor entity would be ideal.
The idea being that the usual 'entity' setting is still used for the setpoint and mode commands, but 'current temperature' is overridden by the reading from 'temperature_entity'.

**Comment by ciotlosm** [comment]
Fixed in #179
