### ISSUE TITLE
Disable shadow on nested cards

### ISSUE THREAD

**Issue by FezVrasta** [ciotlosm/custom-lovelace#186]
If a card is nested inside another (like an entity card) the shadow should be removed from the nested card so that we don't end up with two "levels"

**Comment by ciotlosm** [comment]
A card doesn't know if it's in another card (at least not through init). I guess this could be a config option for the card. Which is the card that you need this on?

**Comment by FezVrasta** [comment]
AFAIK only the entity card supports nested cards, so I'd like to have it for such card, but if others support it as well then it should work there as well

**Comment by iantrich** [comment]
use card-mod
