### ISSUE TITLE
Hide disarm

### ISSUE THREAD

**Issue by jaburges** [ciotlosm/custom-lovelace#198]
Hi there, 
more enhancement, but not sure where to raise. 

Love the alarm card (thank you!!)

I dont want to use a code and so dont want 'disarm' visible in the UI as I have panels round the house. Apologies i cant code well enough to edit the js :(

**Comment by ciotlosm** [comment]
Hey @jaburges what would be the use case? With or without the code this panel would require you to be able to use arm/disarm.

If you plan to just show the state of the alarm somewhere you're better of with a different entity that just displays state (like https://www.home-assistant.io/lovelace/picture-entity/ with state images)

**Comment by jaburges** [comment]
Apologies for some reason I never got an alert about this response. Thanks for coming back to me.
