### ISSUE TITLE
Request:  Add JSON to repos for Custom Updater compliance

### ISSUE THREAD

**Issue by rpitera** [ciotlosm/custom-lovelace#201]
[Custom Updater](https://github.com/custom-components/custom_updater)

This project is doing a great job of helping us keep up with updates to custom cards and components.  Would be awesome if you could help by setting up the required JSON entries for your cards so we knew when there was an update!  Thanks

**Comment by ciotlosm** [comment]
@rpitera I think this is already done. Any merge in this repository triggers an upstream job in that specific project and it creates the json files. I already use the card-tracker that I helped build to update my cards as well :-)

**Comment by jchasey** [comment]
Hi, are there any instructions on how to setup the automatic creation of the json files etc? I have been helping with a custom component that we would be interested in adding this support.

**Comment by ciotlosm** [comment]
I think it's best to move the component in the appropriate repo (https://github.com/custom-components).  I have moved some of those that were originally here in the repositories there and probably will more more in the future, but if you start fresh I recommend you start there. You would be the owner of your project but would get the benefit of the updater out of the box without any extra custom integration.

**Comment by rpitera** [comment]
I see what my problem was now; I didn't have the version numbers entered for all of your cards.  Once I updated this in ui-lovelace.yaml and restarted HA, everything appeared.  Sorry to have missed this - the error was mine.  Thanks for your great work on Lovelace and for supporting custom updater!
