### ISSUE TITLE
Enhancement: Set temp by dragging/rotating dial for thermostat card

### ISSUE THREAD

**Issue by jpcaldwell30** [ciotlosm/custom-lovelace#205]
For the thermostat card, in the original element on codepen, the temperature can be set by clicking the thermostat for 1 second and then dragging which "rotates" the dial. It would be great if this functionality could be added to the card because it allows for much quicker setting of the temperature without having to click a bunch of times.

**Comment by ciotlosm** [comment]
@jpcaldwell30 It depends on personal preference. After testing on smaller devices and with mouse on desktop, the drag was not really that reliable and sometimes ended up moving the temperature in unpredictable ways. 

If there are more votes on this (as this feature competes with others on my list) I'd look into adding this in as a config option, but for now the benefit vs implementation complexity doesn't seems like it's worth it.

**Comment by jolaca01** [comment]
+1 to this. It would be the best functionality to add in my opinion, as it would mean it is behaving really as the original nest.
