### ISSUE TITLE
Custom Attribute on Entities possible?

### ISSUE THREAD

**Issue by XRyu** [ciotlosm/custom-lovelace#208]
Is it possible to select an other attribute for "secondary_info" than entity_id/last-change? 
i would love to select an attribute from a sensor (like "magic_title" of the Tautulli-Sensor)

**Comment by ciotlosm** [comment]
@XRyu Are you refering to the official Lovelace entities card? Or which is the card that you're looking for this information?

This repository has only custom cards

**Comment by XRyu** [comment]
@ciotlosm Not sure (i am pretty new to lovelace)
I am doing this in the lovelace-config:

`- type: custom:monster-card
        card:
          type: entities
          title: Wer schaut was?
        filter:
          include:
            - entity_id: "sensor.tautulli_*"
              options:
                secondary_info: last-changed
`

instead of last-changed i would love to use an other attribute :)

**Comment by ciotlosm** [comment]
Unfortunately the custom card can't make changes on the functionality exposed by 'entities' card. You will need to ask for such an enhancement on the official lovelace repository.
