### ISSUE TITLE
[FR] Can we change the font color?

### ISSUE THREAD

**Issue by xbmcnut** [ciotlosm/custom-lovelace#210]
Hey there,

Love this but it'd be great if we could manipulate the font color. Is that possible? Using it to display next tide tide time which is just text and it'd be great if I could make that blue.

![image](https://user-images.githubusercontent.com/1492137/46982791-432b0000-d13a-11e8-923f-75124a2d7b9f.png)

**Comment by iantrich** [comment]
card moved: https://github.com/custom-cards/bignumber-card
