### ISSUE TITLE
One thermostat not working properly

### ISSUE THREAD

**Issue by dustins1983** [ciotlosm/custom-lovelace#217]
I have 2 next 3rd gen thermostats that work properly using the traditional HA thermostat page.

The first tstat works perfectly, and shows where heat and ac are set to  along with ambient temp.

The second one will show ambient temp, but will not show where it is currently set. Also this same thermostat does not adjust properly.

Say if it was set to 60 heat and 78 cool. If I change heat from 60, it automatically goes to 70, and then cant go back down to 60. The other tstat doesn't do that.

I have tested using just the problem one without including the working one and no change. The one that doesnt work, doesnt work if its by itself, or together with the working one.

![screenshot_20181022-161812_chrome](https://user-images.githubusercontent.com/44380593/47317901-a7f1c900-d618-11e8-8a56-acd3d540096d.jpg)
![screenshot_20181022-161816_chrome](https://user-images.githubusercontent.com/44380593/47317907-aaecb980-d618-11e8-9d6c-b145b358653a.jpg)

In the images see on the top one it shows the marks where the ac is set. The bottom it does not. I also know the bottom (problem one) does not change color when it comes on. I have not tested that with the top one.

Thanks so much for this awesome project, it is so cool. I dont know how you guys and gals do this stuff!!

**Comment by ciotlosm** [comment]
It might be that this is a bug based on how the object are setup in the repo. I'm working on a new version that has better setup and uses typescript (still retro-fit of current one). 

Maybe give that a try at some point.
