### ISSUE TITLE
[monster-card] suggestion : decide which value to show for an entity.

### ISSUE THREAD

**Issue by prigal** [ciotlosm/custom-lovelace#219]
Hello,

Following some comments here : https://community.home-assistant.io/t/lovelace-bringing-back-entity-filter-monster-card/58701/65

We would like to be able to show battery percentage (alt value) as entity value and not the main value.

Egs : low battery alert (in french) for temperature sensors showing the main value (temperature) and not the battery level.

![capture d ecran 2018-10-29 a 07 44 37](https://user-images.githubusercontent.com/895267/47633569-a4959a80-db4e-11e8-9092-6b3778fbcb69.png)

To fix this actually, I can create a template sensor per sensor, but it would be great to see this option directly in monster card.

Thanks.

**Comment by iantrich** [comment]
card has moved: https://github.com/custom-cards/monster-card
