### ISSUE TITLE
enhancement : thermostat card , to work cool and heat with std generic thermostat

### ISSUE THREAD

**Issue by gnkarn** [ciotlosm/custom-lovelace#220]
as the generic thermostat component is not able to work , on a heat or cool mode ( i also tested the one under development that is prepared for this ,  but is not working right ) , then one straight forward way to implement it by using std generic thermostat is configuring two of them ( one heat , one cool ), in my case targeting the same switch , as the switch itself hold the right ON command when the mode is heat , and when the mode is cool .

So the request is , if it can be included on the card code the ability to config, two device_ids  for thermostat , one for the cool control thermostat , and one for the Heat mode control thermostat .

this way people using generic thermostat ( the current version, that cant do both ), would use just one interface instead of two .

**Comment by ciotlosm** [comment]
I'm not sure I understand the actual issue. If you have both heating and cooling defined, you should have two set-points and these should show up in the thermostat UI.
