### ISSUE TITLE
custom alarm_control_panel-card "clear" button size fail

### ISSUE THREAD

**Issue by kvvoff** [ciotlosm/custom-lovelace#223]
Hello! How can I change the size or the names of the buttons? The "clear" button on my tongue spoiled the whole look.
![clear](https://user-images.githubusercontent.com/38342171/49272048-2bf16900-f481-11e8-973c-1d646bf0370d.png)

**Comment by ciotlosm** [comment]
@kvvoff this card is no longer supported. Please try and switch to the official: https://www.home-assistant.io/lovelace/alarm-panel/
