### ISSUE TITLE
Gauge card - Using entities/templates for min/max values

### ISSUE THREAD

**Issue by hulkhaugen** [ciotlosm/custom-lovelace#225]
I would like the possibility to use a sensor value as minimum and maximum level for a gauge card. I have data provided from my power company, and one day the prices might vary between 0.3-0.5 pr kWh, while others might be between 0,8 and 1,8 pr kWh. So I would like the min and max to be relative to the price variations of that day.

A bonus would be to be able to specify color based on percent of the specified min/max values. So say green from <50%, amber from 50-80% and red >80% of the values in min/max, which might be 0.4/0.85 for instance.

**Comment by iantrich** [comment]
card moved: https://github.com/custom-cards/gauge-card
