### ISSUE TITLE
Problem with Home Assistant 0.84.3

### ISSUE THREAD

**Issue by labachev** [ciotlosm/custom-lovelace#229]
All of these custom cards don't work in Home Assistant 0.84.3

**Comment by Jeltel** [comment]
Try putting the location of the resource in via the raw configure mode.

`resources:
  - type: js
    url: /local/monster-card/monster-card.js?v0`

**Comment by labachev** [comment]
The problem was:
Uncaught SyntaxError: Unexpected identifier

Fixed.
