### ISSUE TITLE
home-setter broken on 0.86

### ISSUE THREAD

**Issue by wbilger** [ciotlosm/custom-lovelace#238]
Just seem to get the spinner, forever.

**Comment by ciotlosm** [comment]
in 0.86 lovelace has become the default interface. You should not need home-setter anymore. I will update in the next days documentation around this.

**Comment by wbilger** [comment]
I see you reopened this, did you have further thoughts? I really like this
card, the ability to set the start screen per device is really nice.
I know you can just edit the start page on kiosk, but in a family setting,
I set their Kiosk browsers up on their phones, and they can set the "Start
Page" and change it themselves anytime.

**Comment by acordill** [comment]
I'm having the same problem.  When I go to https://mywebsite:8123/ it just sits there on the current page with the only difference other than the new address in the Chrome address bar.  If I then hit refresh or anything it just sits and spins like @wbilger said.

**Comment by iantrich** [comment]
card moved: https://github.com/custom-cards/home-setter
