### ISSUE TITLE
No icons in alarm panel card

### ISSUE THREAD

**Issue by Hertizch** [ciotlosm/custom-lovelace#240]
I'm on 0.87 and the alarm panel card does not show icons for any state, just the circle.
[Imgur](https://i.imgur.com/tGV88TL.png)

**Comment by raccettura** [comment]
this.icons needs to be updated to something like:

`    this._icons = {
      'armed_away': 'hass:shield-lock',
      'armed_custom_bypass': 'hass:security',
      'armed_home': 'hass:shield-home',
      'armed_night': 'hass:shield-home',
      'disarmed': 'hass:shield-check',
      'pending': 'hass:shield-outline',
      'triggered': 'hass:bell-ring',
    }
`

**Comment by Hertizch** [comment]
Thanks, that did it!

**Comment by michel72** [comment]
Same here, hoping for a fix from the author, so I can use the tracker-card.

**Comment by Hertizch** [comment]
I've made a pull request #241 regarding this

**Comment by ciotlosm** [comment]
This is no longer supported. Please use: https://www.home-assistant.io/lovelace/alarm-panel/
