### ISSUE TITLE
Alarm card: Buttons "missing" after 0.88 upgrade

### ISSUE THREAD

**Issue by BertilJ** [ciotlosm/custom-lovelace#244]
Looks like the buttons are missing after 0.88 upgrade, probably due to the breaking change announced regadarding this.

The card is still usable, but it looks kind of strange now.

**Comment by Hertizch** [comment]
Replace `paper-button` with `mwc-button`

**Comment by ezraholm50** [comment]
I've replaced all `paper-button` with `mwc-button` but it still doesnt show, any idea?

**Comment by ciotlosm** [comment]
For which card is this?

**Comment by iantrich** [comment]
probably alarm panel

**Comment by ciotlosm** [comment]
@iantrich thanks

**Comment by jscott304** [comment]
Any update on the button issue? I tried doing the mwc-button replace with no luck

**Comment by ciotlosm** [comment]
@jscott304 @BertilJ Unfortunately this card is no longer supported (at least in this repository). I recommend you switch to the official one here: https://www.home-assistant.io/lovelace/alarm-panel/
