### ISSUE TITLE
card does not load after update to HA v0.88.1

### ISSUE THREAD

**Issue by Valiceemo** [ciotlosm/custom-lovelace#246]
After updating to HA v088.1 the gauge card does not load.
error message is:
Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree

**Comment by houfukude** [comment]
same problem.

**Comment by billyabong** [comment]
This can be resolved if you edit the gauge-card.js file, removing line 24 `const shadow = card.attachShadow({ mode: 'open' });`.

Make sure to do a hard refresh in your broswer afterwards tho.

**Comment by VDRainer** [comment]
@billyabong , YOU ARE A HERO!! :heart:

**Comment by iantrich** [comment]
card has moved: https://github.com/custom-cards/gauge-card
