### ISSUE TITLE
How to change Thermostat colour from Blue to Black and vice versa? 

### ISSUE THREAD

**Issue by jerrychong25** [ciotlosm/custom-lovelace#249]
Hi all,

After installed this Thermostat card in HA, my Thermostat default colour is Blue.

How could I do to change from Blue to Black colour and vice versa?

Thanks.

**Comment by ciotlosm** [comment]
Either edit the card code directly or wait for an enhancement to options to support this.

**Comment by jerrychong25** [comment]
@ciotlosm Will wait for enhancement options for this.

Thanks!

**Comment by jerrychong25** [comment]
No longer using Home Assistant. Will close this issue.

Thanks all!
