### ISSUE TITLE
Where to put the JS files?

### ISSUE THREAD

**Issue by patrickjane** [ciotlosm/custom-lovelace#255]
I have a manual home assistant installation using the [venv / other user method](https://www.home-assistant.io/docs/installation/raspberry-pi/). As a result, I do have the HA installation in `/srv/homeassistant` (python files), and the configuration in `/home/homeassistant/.homeassistant`.

Thus, I do not have a `www` folder, nor a `config` folder. For using custom lovelace cards, I figured I need to go into raw mode, and add something like:
```
resources:
  - type: js
    url: /local/group-card/group-card.js?v0
``` 
to the top or the bottom.

However, where is `url` located? E.g. where is `/local` pointing to in all the examples?

I tried to use `url: /group-card/group-card.js?v0` and clone the group-card repo into `/home/homeassistant/.homeassistant/group-card`, however it wont recognize the card.

Where do I need to put the JS files?

**Comment by ciotlosm** [comment]
Group card is no longer supported in this repo
