### ISSUE TITLE
Set Temperature is not shown correct 

### ISSUE THREAD

**Issue by b3ster** [ciotlosm/custom-lovelace#257]
Hi, first thanks a lot for your work, we really love this :)

Please see the screenshot for error description:

![settemp_console](https://user-images.githubusercontent.com/28812766/73348287-6de68c80-4289-11ea-9819-19632bf42025.PNG)

Please let me know which information could be helpful for analyses :)

**Comment by ciotlosm** [comment]
This problem will get fixed in the new version. I will close the issue as it will be a big refactoring. See https://github.com/ciotlosm/lovelace-thermostat-dark-card
