### ISSUE TITLE
problem with alarm control panel

### ISSUE THREAD

**Issue by smarthome3b** [ciotlosm/custom-lovelace#258]
I paste it in my ui-lovelace.yaml file :

``` 
- type: custom:alarm_control_panel-card
        entity: alarm_control_panel.signalizatsiia
```

and get this in google chrome error with not admin user:

`Cannot add property states, object is not extensible`

and this in safari with admin user: 

`Attempted to assign to readonly property.`

HA v108.9

**Comment by ciotlosm** [comment]
@smarthome3b I recommend you switch for now to the official alarm control panel from Home Assistant (https://www.home-assistant.io/lovelace/alarm-panel/)
