### ISSUE TITLE
Orange

### ISSUE THREAD

**Issue by lancelon** [ciotlosm/custom-lovelace#259]
Could have sworn when I first installed this card, when the thermostat went into heating mode, the thermostat lovelace display turned orange like the nest itself does? It doesn't do this now...?
The other thing I could have sworn it used to do is display a 'leaf' when we were in eco mode, again, doesn't do this now?
Am I going mad? Making things up?
Thanks

**Comment by ciotlosm** [comment]
The addon requires a big remake for the new version of Home Assistant. I will close this issue for now and retest once I get to it.

**Comment by ciotlosm** [comment]
This should be fixed.
