### ISSUE TITLE
add the outside temperature

### ISSUE THREAD

**Issue by Vorms** [ciotlosm/custom-lovelace#263]
Hello,
I use Sinope thermostat.
This card do very well the job !
I discover some bug on the thermostat.
It will be very welcome if it is possible to add the outside temperature, and the legend of the graph...
It will also be cool if it is possible to change the time scale in the history.

Many thanks for your help.
Best regards
Thierry

**Comment by ciotlosm** [comment]
You should be able to add using `ambient_temperature` config. 
The details view I will add as a "config" cog later on in the new refactoring.
