### ISSUE TITLE
Improve versioning for users

### ISSUE THREAD

**Issue by ciotlosm** [ciotlosm/custom-lovelace#31]
Add versioning to cards. This should permit users to:
- Find out when new versions are out
- Get a change-log of updates
- Allow for easier cache busting than manual ?v=X

**Comment by ciotlosm** [comment]
- Added VERSION file in card folder that will get incremented manually on new features or bug fixes.
- Changelog will be added on next version increment

For cache bust users might need to use a custom script to update resources automatically and append v=VERSION based on VERSION files in the repo.

**Comment by kylerw** [comment]
Is this local or intended to allow us to update from your repo? Would love a way to be notified if updates exist in the rep!

**Comment by ludeeus** [comment]
@kylerw sounds like you want these:
https://github.com/custom-components/custom_cards
https://github.com/custom-components/sensor.custom_cards

**Comment by ciotlosm** [comment]
Draft card here: https://github.com/ciotlosm/custom-lovelace/tree/update_sensor/cardtracker-card

**Comment by ciotlosm** [comment]
Implemented in master. Needs some docs updated on backend side.
