### ISSUE TITLE
plan-coordinates doesn't work when panel: true

### ISSUE THREAD

**Issue by kylerw** [ciotlosm/custom-lovelace#47]

**Comment by ciotlosm** [comment]
This is expected, because `panel: true` will load only 1st card in view, and panel-coordinates is a card. However working in non panel mode will still give you same coordinates as it's % based.

**Comment by ciotlosm** [comment]
@kylerw can you try to use a horizontal-stack with panel: true and inside the horizontal stack to use both the plan-coordinates and picture-elements?

**Comment by kylerw** [comment]
@ciotlosm that does work - pushes the image to one side or the other (depending what card you put first). This is actually nice because it fits to height rather than width and requiring a scroll but on smaller screens doesn't display as well.

![image](https://user-images.githubusercontent.com/370860/42702335-6c29fd0c-8686-11e8-8fb2-01b053a2c408.png)



![image](https://user-images.githubusercontent.com/370860/42702379-8e64472e-8686-11e8-8d5a-3c522b7fd785.png)

**Comment by kylerw** [comment]
vertical-stack actually works best and closest to what you would expect - 

![image](https://user-images.githubusercontent.com/370860/42702482-e3385538-8686-11e8-886c-28c8360c0152.png)


now for a feature request for an option to fit picture-element with panel: true to width rather than height.

**Comment by kylerw** [comment]
I'll try to put something together. Thanks for the help and guidance.
