### ISSUE TITLE
Bignumber to support meter style background

### ISSUE THREAD

**Issue by cogneato** [ciotlosm/custom-lovelace#7]
Card that fills with color meter-style horizontally or vertically. Maybe as an option for bignumber? Could be used together with horizontal stacks to create a row of meters or combined with gauges and bignumber.

**Comment by ciotlosm** [comment]
Adding this http://jsfiddle.net/75Umu/3/ to use as base CSS. I probably will implement on top of bignumber. It will get activated when you set min/max.

**Comment by ciotlosm** [comment]
Fixed, see docs
