### ISSUE TITLE
Greeter card

### ISSUE THREAD

**Issue by swetoast** [ciotlosm/custom-lovelace#70]
A Personal greeter card that shows calendar events from calendar sensor and time of day and any additional sensor that the user wants

dynamic backgrounds from unsplash using their api lib already available 

https://github.com/unsplash/unsplash-js

got a mock card layout as a suggestion

![image](https://user-images.githubusercontent.com/2525304/42732499-142daba0-8823-11e8-8d99-183c54aee90b.png)

**Comment by ciotlosm** [comment]
Can this be done with template sensors and picture-elements?

**Comment by swetoast** [comment]
dont know yet reinstalled from the botched update that ballop pushed

**Comment by swetoast** [comment]
can be done via picture elements
