### ISSUE TITLE
Alarm card doesn't show keypad

### ISSUE THREAD

**Issue by gwww** [ciotlosm/custom-lovelace#71]
The alarm card does not show the keypad because it is checking if code_format return type is a Number. Many panels that exist in the current components for homeassistant return code_type as a string regex.

**Comment by loudmicro** [comment]
same here! intrested in how to fix it

**Comment by ciotlosm** [comment]
This is a bug (ported from the original card) that will get fixed with a configuration setting. This will allow for either auto detection of code type (like now) or a variable to force keypad to display. 

This will be added in the next Alarm card release

**Comment by ciotlosm** [comment]
Fixed in dev, will merge to master once I fix #73 as well

**Comment by ciotlosm** [comment]
Fixed in master now
