### ISSUE TITLE
Alarm card: allow "auto enter" after set number of digits

### ISSUE THREAD

**Issue by gwww** [ciotlosm/custom-lovelace#72]
After a configured number of digits are entered, say 4, automatically call the service with the code. Allow the user to press "away", "home", etc before code is submitted and that becomes the arm type that is sent with the code.

Example config: 
`auto_arm_length: 4`
`default_auto_arm: arm_away`

Example UX:
User presses "Arm home" (this changes from the default arm_away) 
User presses 4 digits and after pressing the 4th digit service is called with arm_home and the 4 digits.
Text field clears, arm_away set as default button again. Card updates according to whatever state changes as it does now.

**Comment by ciotlosm** [comment]
I don't think I will implement in first iteration overriding of default button from the UI. I think config should look like:

```yaml
auto_arm:
  code_length: 4
  action: arm_away
```

**Comment by iantrich** [comment]
I would think an `auto_disarm` configuration would fall within this scope as well?

**Comment by gwww** [comment]
I have an implementation of this. It supports both the existing UX and the "`auto_arm`" UX. The code is heavily refactored from the existing. It support both arm/disarm automatically when the set number of digits are entered.

I will be posting it on my GitHub account, probably tonight. There's at least one bug that I know of in my testing. I'd be just as happy if this merges with the existing, but I have not communicated with @ciotlosm about that yet. 

I was going to switch `auto_arm` to `auto_enter`. I was also going to switch action to `arm_action`.

Feedback welcome.

**Comment by ciotlosm** [comment]
I will have a look latest on Monday in more details. Sounds like a great idea and happy to get a PR for this. I'm currently away because of a big festival in town so less time to look at code with proper attention.

**Comment by ciotlosm** [comment]
I will merge in master once last of TODO in dev are complete.
