### ISSUE TITLE
Colors/icons for alarm card

### ISSUE THREAD

**Issue by arsaboo** [ciotlosm/custom-lovelace#73]
As discussed on Discord, we should probably change the colors on the card to make them in line with the standard practice. I am attaching a few examples that I found online that should make the color choices clear:

![image](https://user-images.githubusercontent.com/18319734/42738171-59632748-884d-11e8-96dc-988d2a47a6d8.png)
![image](https://user-images.githubusercontent.com/18319734/42738202-c6304522-884d-11e8-9738-2cc70d4227d7.png)
![image](https://user-images.githubusercontent.com/18319734/42738203-cd459718-884d-11e8-8485-ed78208e08a6.png)

Looks like Green for disarmed, Amber for Home/Night, and Red for Armed is the way to go. 

Padlocks (open/close) with the right colors should be perfect for icons.

**Comment by ciotlosm** [comment]
![alarm](https://user-images.githubusercontent.com/7738048/42747472-2e456128-88e5-11e8-80ba-2521721dd291.gif)

**Comment by ciotlosm** [comment]
Fixed in master now
