### ISSUE TITLE
Lock Card

### ISSUE THREAD

**Issue by alex-savin** [ciotlosm/custom-lovelace#75]
Thank You for you work!

I would like to ask a new Lock Card!
Something like this

![lock-card](https://user-images.githubusercontent.com/10366351/42739415-e2d0d216-8864-11e8-9704-cccda2219e7a.png)

**Comment by ciotlosm** [comment]
Is there a `demo:` component that emulates an entity that you'd like to control with such a card?

**Comment by alex-savin** [comment]
I think that should be `lock` at https://www.home-assistant.io/components/demo/

**Comment by alex-savin** [comment]
@ciotlosm is it possible to add some animation. As an example, when you click on settings icon, it's going to extend a card by opening from bottom some other panels?!

**Comment by ciotlosm** [comment]
@alex-savin animation yes, but usually I try to avoid layout changing animations. What would it be under that settings icon?

**Comment by iantrich** [comment]
@alex-savin What does a custom lock card give you that can't be had with something like an `entities` card?

https://www.home-assistant.io/lovelace/entities/

**Comment by ciotlosm** [comment]
In 0.74 this will be achievable with picture-elements in the exact style you want

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
