### ISSUE TITLE
Gauge Ok in Chrome Ko in Firefox

### ISSUE THREAD

**Issue by sdomotica** [ciotlosm/custom-lovelace#9]
Firefox
![immagine](https://user-images.githubusercontent.com/781294/42411334-55944420-81fa-11e8-843f-6744f31c30db.png)
Chrome
![immagine](https://user-images.githubusercontent.com/781294/42411344-69007380-81fa-11e8-8721-cf50524a4571.png)

**Comment by ciotlosm** [comment]
I will have a look tomorrow

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ciotlosm** [comment]
@sdomotica can you try it now with latest card version?

**Comment by sdomotica** [comment]
I'm running offical 0.73 and I use your last released version
![immagine](https://user-images.githubusercontent.com/781294/42423724-a00c4d30-82ff-11e8-934f-d380cd3091d0.png)

**Comment by ciotlosm** [comment]
Woups! My push was rejected, forgot to rebase. Can you please try now?

**Comment by sdomotica** [comment]
standalone now works, but inside horizontal not
![immagine](https://user-images.githubusercontent.com/781294/42424343-2ecb016e-830b-11e8-93ba-508b330ee0db.png)
Chrome it's ok
![immagine](https://user-images.githubusercontent.com/781294/42424347-3c8cb3f6-830b-11e8-962a-47207342e569.png)

**Comment by ciotlosm** [comment]
I will have a look in the afternoon. I tested Chrome and Opera but Firefox I only have on other computer (and there are restrictions to install it)

**Comment by ciotlosm** [comment]
@sdomotica I did some updates with shadowroot that might isolate style a bit more. Not sure if it fixes anything as I haven't tested, but maybe you can give it a go.

I also updated bignumber card to include "Scale" so you can use the same "scale" on both cards and they will match height.

**Comment by ciotlosm** [comment]
Ok, found the problem. On your setup you need to go do:
```
about:config
```
and the set to true:
```
dom.webcomponents.customelements.enabled
```
and
```
dom.webcomponents.shadowdom.enabled
```
